apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: development
  labels:
    app: identity
spec:
  type: NodePort
  selector:
    app: identity
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
